
import {
  Coins, Sword, Shield, Moon, Pencil, HelpCircle, Zap, Brain, Heart, Skull, Star, Gem, Settings,
  PlusCircle, MinusCircle, XCircle, CheckCircle2, AlertTriangle, Info, Wand2, Sparkles, Sun, Cloud,
  Flame, Leaf, Droplets, Feather, Eye, Swords, ShieldCheck, ShieldAlert, Aperture, Book, Camera,
  Castle, Crown, Diamond, Dice5, Flag, Flower, Gift, Globe, KeyRound, Lightbulb, Lock, MapPin, Medal,
  Mountain, Music, Package, Palette, PawPrint, Phone, Puzzle, Rocket, Save, Search, Ship, Sprout,
  Ticket, Trash2, TreePine, Trophy, Umbrella, User, Video, Wallet, Watch, Wifi, Wrench
  // Add other icons here if explicitly needed by name elsewhere
} from 'lucide-react';
import type * as LucideIconsAll from 'lucide-react'; // For the type

// Centralized map of string names to Lucide icon components
export const lucideIconsMap: { [key: string]: React.ElementType<LucideIconsAll.LucideProps> } = {
  "Coins": Coins,
  "Sword": Sword,
  "Shield": Shield,
  "Moon": Moon,
  "Pencil": Pencil,
  "HelpCircle": HelpCircle,
  "Zap": Zap,
  "Brain": Brain,
  "Heart": Heart,
  "Skull": Skull,
  "Star": Star,
  "Gem": Gem,
  "Settings": Settings,
  "PlusCircle": PlusCircle,
  "MinusCircle": MinusCircle,
  "XCircle": XCircle,
  "CheckCircle2": CheckCircle2,
  "AlertTriangle": AlertTriangle,
  "Info": Info,
  "Wand2": Wand2,
  "Sparkles": Sparkles,
  "Sun": Sun,
  "Cloud": Cloud,
  "Flame": Flame,
  "Leaf": Leaf,
  "Droplets": Droplets,
  "Feather": Feather,
  "Eye": Eye,
  "Swords": Swords,
  "ShieldCheck": ShieldCheck,
  "ShieldAlert": ShieldAlert,
  "Aperture": Aperture,
  "Book": Book,
  "Camera": Camera,
  "Castle": Castle,
  "Crown": Crown,
  "Diamond": Diamond,
  "Dice5": Dice5,
  "Flag": Flag,
  // "Flash" was removed as it caused build issues
  "Flower": Flower,
  "Gift": Gift,
  "Globe": Globe,
  "KeyRound": KeyRound,
  "Lightbulb": Lightbulb,
  "Lock": Lock,
  "MapPin": MapPin,
  "Medal": Medal,
  "Mountain": Mountain,
  "Music": Music,
  "Package": Package,
  "Palette": Palette,
  "PawPrint": PawPrint,
  "Phone": Phone,
  "Puzzle": Puzzle,
  "Rocket": Rocket,
  "Save": Save,
  "Search": Search,
  "Ship": Ship,
  "Sprout": Sprout,
  "Ticket": Ticket,
  "Trash2": Trash2,
  "TreePine": TreePine,
  "Trophy": Trophy,
  "Umbrella": Umbrella,
  "User": User,
  "Video": Video,
  "Wallet": Wallet,
  "Watch": Watch,
  "Wifi": Wifi,
  "Wrench": Wrench
}; // Ensure this closing brace and semicolon are present
